In [4]:
import pandas as pd 
import numpy as np 
data = {'one': pd.Series([1, 2, 5], 
                             index=['a', 'b', 'e']),
        'two': pd.Series([1, 2, 3, 4], 
                             index=['a', 'b', 'c', 'd'])}
table = pd.DataFrame(data)
print("Before:\n",table)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(table)
imputed_data = imputer.transform(table.values)
print("After:\n",pd.DataFrame(imputed_data, columns=['one','two']))


Before:
    one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN
After:
         one  two
0  1.000000  1.0
1  2.000000  2.0
2  2.666667  3.0
3  2.666667  4.0
4  5.000000  2.5


C:\Users\Kalpesh__K__\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


In [5]:
import pandas as pd
data = {'Customer_id': pd.Series([1,2,3,4,5]),
        'Loan_type': pd.Series(['Home Loan',
                                'Personal Loan',
                                'Education Loan',
                                'Home Loan',
                                'Credit Loan']),
        'Income': pd.Series(['30K','25K',
                        '15K','40K','35K'])}
loan_info = pd.DataFrame(data)
print(loan_info)



   Customer_id       Loan_type Income
0            1       Home Loan    30K
1            2   Personal Loan    25K
2            3  Education Loan    15K
3            4       Home Loan    40K
4            5     Credit Loan    35K


In [6]:
import pandas as pd
data = {'Customer_id': pd.Series([1,2,3,4,5]),
        'Loan_type': pd.Series(['Home Loan',
                                'Personal Loan',
                                'Education Loan',
                                'Home Loan',
                                'Credit Loan']),
        'Income': pd.Series(['30K','25K',
                        '15K','40K','35K'])}
loan_info = pd.get_dummies(loan_info, 
                        prefix_sep='_', 
                        drop_first=False)
print(loan_info)


   Customer_id  Loan_type_Credit Loan  Loan_type_Education Loan  \
0            1                      0                         0   
1            2                      0                         0   
2            3                      0                         1   
3            4                      0                         0   
4            5                      1                         0   

   Loan_type_Home Loan  Loan_type_Personal Loan  Income_15K  Income_25K  \
0                    1                        0           0           0   
1                    0                        1           0           1   
2                    0                        0           1           0   
3                    1                        0           0           0   
4                    0                        0           0           0   

   Income_30K  Income_35K  Income_40K  
0           1           0           0  
1           0           0           0  
2           0           0 

In [7]:
import pandas as pd
data = {'Customer_id': pd.Series([1,2,3,4,5]),
        'Loan_type': pd.Series(['Home Loan',
                                'Personal Loan',
                                'Education Loan',
                                'Home Loan',
                                'Credit Loan']),
        'Income': pd.Series(['30K','25K','15K',
                             '40K','35K'])}
loan_info = pd.DataFrame(data)

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
loan_info_upd=loan_info.apply(labelencoder.fit_transform)
print(loan_info_upd)


   Customer_id  Loan_type  Income
0            0          2       2
1            1          3       1
2            2          1       0
3            3          2       4
4            4          0       3


In [8]:
import numpy as np
from sklearn import preprocessing

data = np.array(
    [[5.1,3.5,1.4,0.2],
     [4.9,3.0,1.4,0.2],
     [4.7,3.2,1.3,0.2],
     [4.6,3.1,1.5,0.2],
     [5.0,3.6,1.4,0.2]])
print('Before Normalization\n',data)

normalized_data = preprocessing.normalize(data)
print('\nAfter Normalization\n',normalized_data)


Before Normalization
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

After Normalization
 [[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]]


In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#import the dataset
df = pd.read_csv("Car_sales.csv")
#drop the unwanted columns
df=df.drop(['4-year resale value','Price in thousands'],axis=1) 
#get correlations of each features in dataset
corr_mat = df.corr()
top_corr_features = corr_mat.index
#plot the figure using matplot lib
plt.figure(figsize=(6,6))
#plot heat map using seaborn
x=sns.heatmap(df[top_corr_features].corr(),annot=True,cmap="RdYlGn")


FileNotFoundError: [Errno 2] No such file or directory: 'Car_sales.csv'